export const CREATE_ORDER = 'CREATE_ORDER';

export const EDIT_ORDER = 'EDIT_ORDER';

export const GET_ORDERS = 'GET_ORDERS';

export const HANDLE_ORDER_NAME = 'HANDLE_ORDER_NAME';

export const HANDLE_ORDER_PHONE_NUMBER = 'HANDLE_ORDER_PHONE_NUMBER';

export const HANDLE_ORDER_ADDRESS = 'HANDLE_ORDER_ADDRESS';

export const HANDLE_ORDER_STATUS = 'HANDLE_ORDER_STATUS';

export const HANDLE_ORDERID_ERROR = 'HANDLE_ORDERID_ERROR';

export const GET_STATISTICS = 'GET_STATISTICS';

export const HANDLE_VALIDATION_ERROR = 'HANDLE_VALIDATION_ERROR';